spring.application.name=8May_SpringDATAJPA_EmployeeCRUDProject

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
spring.datasource.username=root
spring.datasource.password=jatinsoni

# Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Table auto create/update
spring.jpa.hibernate.ddl-auto=update

# SQL query show
spring.jpa.show-sql=true

# SQL formatting
spring.jpa.properties.hibernate.format_sql=true