spring.application.name=SpringBoot_DataJPA_ProjectExample

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdatajpa2May
spring.datasource.username=root
spring.datasource.password=jatinsoni

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create