spring.application.name=03SpringSecurityProject_OAuth
server.port=7878

# ==========================
# Google OAuth2 Configuration
# ==========================
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET

# ==========================
# GitHub OAuth2 Configuration
# ==========================
spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET